### ISSUE TITLE
electric lines

### ISSUE THREAD

**Issue by tomasz13** [hyperknot/hyperpilot#1]
zsolti, ki tudnad emelni a magasfeszultsegu vezetekeket, hogy mindig tokeletesen latszodjanak? koszi

![emohi](https://user-images.githubusercontent.com/12948865/35324794-24537d7e-00f2-11e8-859c-04eb2481dcda.jpg)
![epaks](https://user-images.githubusercontent.com/12948865/35324795-249a5334-00f2-11e8-955d-942b95c106ef.jpg)

**Comment by hyperknot** [comment]
Ki vannak, de csak ha jobban rá vagy zoomolva. Erős lilával vannak színezve. Ki tudod próbálni?
Egyébként Cruiser-GL programmal asztali gépen is lehet tesztelni.
