### ISSUE TITLE
cable cars 

### ISSUE THREAD

**Issue by igortorres** [hyperknot/hyperpilot#5]
Perhaps another representation for the 'cable cars'? But rewritten according to simple syntax:

   
    <m e="way" k="aerialway">
        <line dasharray="20,10" fix="true" stroke="#3e4bc5" width="3.0"/>
    </m>

to:
    <m e="way" k="aerialway">
    <line stroke="#202020" stroke-linecap="butt" stroke-width="0.4"/>
    <line stroke="#202020" stroke-dasharray="2,20" stroke-linecap="butt" stroke-width="4.0"/>
    </m>

![screenshot_20180314-133808](https://user-images.githubusercontent.com/4138694/37419236-be02f348-2792-11e8-992d-3da75fe8dbbd.png)
![screenshot_20180314-133954](https://user-images.githubusercontent.com/4138694/37419237-be2fa76c-2792-11e8-9dcb-27f209a5e1c1.png)

**Comment by hyperknot** [comment]
I think with cablecars and powerlines, I want to purposefully make them ugly and very visible, as they are the biggest dangers for paraglider pilots. I agree that aesthetically it'd be nice to make the look like this, but sometimes it's better to raise awareness. Maybe I can make them a bit softer though. 

Also, did you want to include the code for you version?

**Comment by igortorres** [comment]
You are right, better to be more visible these elements.
I make my version just for fun, I do not intend to use it, I was just curious about how the theme works in XCTrack.
I'll fly with hyperpilot as the default theme.

**Comment by hyperknot** [comment]
Great to hear you are using it, if you ever come up with any improvements just feel to open an issue or PR here.
