### ISSUE TITLE
add place "hamlet"

### ISSUE THREAD

**Issue by igortorres** [hyperknot/hyperpilot#6]
You could add v = "hamlet" in places, with the zoom level that you think is appropriate.
In less populated areas this class is interesting for cross country.

Thanks!

**Comment by hyperknot** [comment]
Thanks for reporting, I've added hamlet, isolated_dwelling and locality.

**Comment by hyperknot** [comment]
They are at zoom 13 or whenever they appear.

**Comment by hyperknot** [comment]
Moved them over to zoom 14 to provide cleaner map.

**Comment by igortorres** [comment]
I already inserted the new version in XC Track, I liked it a lot.
